homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# Enables the frontend
frontend:
  themes: !include themes.yaml

recorder:
  purge_interval: 2
  purge_keep_days: 10

# 設定新增側邊欄
panel_iframe:
  aria2:
    title: Aria2
    icon: mdi:cloud-download
    url: https://your_domain.duckdns.org:6881



# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
 
shopping_list: 
#homekit: !include homekit.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

