version: "2"
services:
  aria2:
    image: wahyd4/aria2-ui:arm32
    container_name: aria2
    network_mode: bridge
    environment:
      - RPC_SECRET=password
      - TZ=Asia/Taipei
    ports:
      - "6443:443"
      - "6800:6800"
      - "6880:80"
    volumes:
      - /home/pi/ssd/sync/aria2:/data
      - ./sslkey/:/root/conf/key
    restart: always
