version: "2"
services:
  aria2:
    image: huangzulin/aria2-ui-pi
    container_name: aria2
    network_mode: bridge
    environment:
      - RPC_SECRET=password
      - TZ=Asia/Taipei
    ports:
      - "6800:6800"
      - "6880:80"
    volumes:
      - /home/pi/ssd/sync/aria2:/data
    restart: always
