version: ‘3.6’
services:
  homebridge:
    image: oznu/homebridge
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - TZ:Asia/Taipei
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - PACKAGES=ffmpeg
