version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /home/pi/ssd/sync/sonarr/downloads:/downloads
      - /home/pi/ssd/sync/sonarr/tv:/tv
    restart: always
  jackett:
    image: linuxserver/jackett:arm32v7-latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - ./config:/config
      - /home/pi/ssd/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
